# Generated by Django 5.2.1 on 2025-05-30 14:50

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=airport.models.create_custom_path
            ),
        ),
    ]
